repo_url: https://github.com/FGA-REQ/2024.2-Gandh
repo_name: 2024.2 - Gandh

site_name: Gandh - Paraíba HotDog Web

nav:
  - Sobre o Projeto: "index.md"
  - Gestão do Projeto:
      - Regras de Negócio: "regras-negocio/regras-negocio.md"
      - Visão do Produto: "visao-produto/visao-produto.md"
      - Requisitos: "doc-requisitos/requisitos.md"
      - Backlog: "backlog/backlog.md"
      - Processo de Desenvolvimento de Software: "BPMN/BPMN.md"
  - Atas de Reunião: 
      - 12/01: "atas-reuniao/atas.md"

theme:
  name: material
  features:
      - navigation.tabs
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Dark mode
      primary: grey
    
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Light mode
      primary: grey
